version: '3.1'
services:
  postgres:
    image: postgres:12.12-alpine3.16
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DATABASE=db
      - POSTGRES_PASSWORD=mamamylaramu
      - POSTGRES_USER=masha
